### ISSUE TITLE
concreate5のインストールをする

### ISSUE THREAD

**Issue by tomokazu-suzuki** [tomokazu-suzuki/cms-infrastructure#4]

**Comment by tomokazu-suzuki** [comment]
## 下記のディレクトリはサーバーで書き込み許可できるようにする必要がある
* packages
* application/config
* application/files

**Comment by tomokazu-suzuki** [comment]
## guiでインストール作業を行っていたらエラーがでた

> mkdir(): Permission denied.
> 
> Trace:
> #0 [internal function]: Whoops\Run->handleError(2, 'mkdir(): Permis...', '/home/wintermoo...', 54, Array) #1 /home/wintermoon/cms/concrete/src/Error/Run/PHP7CompatibleRun.php(36): call_user_func_array(Array, Array) #2 [internal function]: Concrete\Core\Error\Run\PHP7CompatibleRun->__call('handleError', Array) #3 /home/wintermoon/cms/concrete/src/Session/Storage/Handler/NativeFileSessionHandler.php(54): mkdir('/var/lib/php/se...', 511, true) #4 /home/wintermoon/cms/concrete/src/Session/SessionFactory.php(98): Concrete\Core\Session\Storage\Handler\NativeFileSessionHandler->__construct('/var/lib/php/se...') #5 /home/wintermoon/cms/concrete/src/Session/SessionFactory.php(67): Concrete\Core\Session\SessionFactory->getSessionHandler(Object(Concrete\Core\Config\Repository\Repository)) #6 /home/wintermoon/cms/concrete/src/Session/SessionFactory.php(43): Concrete\Core\Session\SessionFactory->getSessionStorage(Object(Concrete\Core\Config\Repository\Repository)) #7 /home/wintermoon/cms/concrete/src/Session/SessionServiceProvider.php(17): Concrete\Core\Session\SessionFactory->createSession() #8 /home/wintermoon/cms/concrete/vendor/illuminate/container/Illuminate/Container/Container.php(498): Concrete\Core\Session\SessionServiceProvider->Concrete\Core\Session\{closure}(Object(Concrete\Core\Application\Application), Array) #9 /home/wintermoon/cms/concrete/src/Application/Application.php(552): Illuminate\Container\Container->build(Object(Closure), Array) #10 /home/wintermoon/cms/concrete/vendor/illuminate/container/Illuminate/Container/Container.php(425): Concrete\Core\Application\Application->build(Object(Closure), Array) #11 /home/wintermoon/cms/concrete/vendor/illuminate/container/Illuminate/Container/Container.php(809): Illuminate\Container\Container->make('session') #12 /home/wintermoon/cms/concrete/src/User/User.php(130): Illuminate\Container\Container->offsetGet('session') #13 /home/wintermoon/cms/concrete/src/User/User.php(47): Concrete\Core\User\User->__construct() #14 /home/wintermoon/cms/concrete/src/Package/StartingPointPackage.php(354): Concrete\Core\User\User::getByUserID(1, true, false) #15 [internal function]: Concrete\Core\Package\StartingPointPackage->add_users() #16 /home/wintermoon/cms/concrete/controllers/install.php(294): call_user_func(Array) #17 [internal function]: Concrete\Controller\Install->run_routine('elemental_blank', 'add_users') #18 /home/wintermoon/cms/concrete/src/Controller/AbstractController.php(161): call_user_func_array(Array, Array) #19 /home/wintermoon/cms/concrete/src/Routing/ControllerRouteCallback.php(27): Concrete\Core\Controller\AbstractController->runAction('run_routine', Array) #20 /home/wintermoon/cms/concrete/src/Routing/Router.php(142): Concrete\Core\Routing\ControllerRouteCallback->execute(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Routing\Route), Array) #21 /home/wintermoon/cms/concrete/src/Support/Facade/Facade.php(119): Concrete\Core\Routing\Router->execute(Object(Concrete\Core\Routing\Route), Array) #22 /home/wintermoon/cms/concrete/src/Application/Application.php(445): Concrete\Core\Support\Facade\Facade::__callStatic('execute', Array) #23 /home/wintermoon/cms/concrete/bootstrap/start.php(230): Concrete\Core\Application\Application->dispatch(Object(Concrete\Core\Http\Request)) #24 /home/wintermoon/cms/concrete/dispatcher.php(36): require('/home/wintermoo...') #25 /home/wintermoon/cms/index.php(2): require('/home/wintermoo...') #26 {main}

**Comment by tomokazu-suzuki** [comment]
* php5.3.3 + httpdであればインストールできた

**Comment by tomokazu-suzuki** [comment]
- [ ] concrete5をインストールするroleを作る
  - [ ] concrete5のソースコードをunzipして/home/wintermoon/cmsにソースコードをコピーしたい
    * unarchiveコマンドを使うと/home/wintermoon/cms/concrete5.7.5.8が作られる⇒unarchiveコマンド後、/home/wintermoon/cmsに concrete5.7.5.8以下のディレクトリとファイルを配置したい

**Comment by tomokazu-suzuki** [comment]
> mkdir(): Permission denied.

php-fpm.d/www.conf に記述されているsession.save_pathが存在しなかったので以下を試したら上記のエラーは解消された

```
mkdir /var/lib/php/session
chown :nginx /var/lib/php/session
```

**Comment by tomokazu-suzuki** [comment]
これも必要
```
chown :nginx application/files/cache
```
